spring.application.name=myproject

spring.datasource.url=jdbc:postgresql://localhost:5432/song_db
spring.datasource.username=postgres
spring.datasource.password=9443426992a

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
